// <auto-generated />
namespace CourierService.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Manage_Table_For_Practices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manage_Table_For_Practices));
        
        string IMigrationMetadata.Id
        {
            get { return "202105240743046_Manage_Table_For_Practices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
