// <auto-generated />
namespace CourierService.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_CancelRemarks_in_orderlog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_CancelRemarks_in_orderlog));
        
        string IMigrationMetadata.Id
        {
            get { return "202104291121159_add_CancelRemarks_in_orderlog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
