// <auto-generated />
namespace CourierService.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BaseEntity_INTO_Task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseEntity_INTO_Task));
        
        string IMigrationMetadata.Id
        {
            get { return "202105050751535_BaseEntity_INTO_Task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
