// <auto-generated />
namespace CourierService.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_fields_In_OrderTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_fields_In_OrderTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202105310535596_Add_fields_In_OrderTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
