// <auto-generated />
namespace CourierService.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addCompletedRemarks_field_In_Orders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCompletedRemarks_field_In_Orders));
        
        string IMigrationMetadata.Id
        {
            get { return "202106081149339_addCompletedRemarks_field_In_Orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
